import { createContext, useContext, useState, useEffect, ReactNode } from "react";

type Language = "ar" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  ar: {
    // Common
    "common.loading": "جاري التحميل...",
    "common.welcome": "مرحباً بك في",
    "app.name": "منصة ابراج التعليمية",
    "app.tagline": "منصه للتعليم الاكتروني",
    "app.description": "منصه للتعليم الاكتروني",
    
    // Navigation
    "nav.browse": "تصفح الدورات",
    "nav.my_learning": "تعلمي",
    "nav.dashboard": "لوحة التحكم",
    "nav.sign_in": "تسجيل الدخول",
    "nav.get_started": "ابدأ الآن",
    "nav.logout": "تسجيل الخروج",
    
    // Notifications
    "notifications.title": "الإشعارات",
    "notifications.unread": "غير مقروء",
    "notifications.no_notifications": "لا توجد إشعارات",
    
    // Home Page
    "home.hero_title": "منصة ابراج التعليمية",
    "home.hero_subtitle": "منصه للتعليم الاكتروني",
    "home.get_started": "ابدأ مجاناً",
    "home.browse_courses": "تصفح الدورات",
    "home.stats.courses": "دورة",
    "home.stats.students": "طالب",
    "home.stats.teachers": "معلم خبير",
    "home.stats.rating": "تقييم متوسط",
    "home.featured_courses": "الدورات المميزة",
    "home.view_all": "عرض الكل",
    "home.how_it_works": "كيف يعمل",
    "home.step1.title": "تصفح الدورات",
    "home.step1.description": "استكشف كتالوج دوراتنا عبر مختلف الفئات",
    "home.step2.title": "سجّل وتعلم",
    "home.step2.description": "تواصل معنا عبر واتساب للتسجيل في الدورات المدفوعة أو ابدأ التعلم فوراً مع الدورات المجانية",
    "home.step3.title": "حقق الأهداف",
    "home.step3.description": "أكمل الاختبارات، تتبع تقدمك، وأتقن مهارات جديدة",
    "home.view_course": "عرض الدورة",
    "home.no_courses_category": "لا توجد دورات في هذه الفئة. جرب فئة أخرى.",
    "home.no_courses_available": "لا توجد دورات متاحة بعد. تحقق مرة أخرى قريباً!",
    "home.platform_highlight": "دورات لمختلف الصفوف والمواد مع أفضل الأساتذة على مستوى العراق",
    "home.platform_highlight_desc": "انضم لآلاف الطلاب الذين يتعلمون مع نخبة من المعلمين المتميزين",
    
    // Courses
    "courses.title": "استكشف دوراتنا",
    "courses.subtitle": "اكتشف دورات في البرمجة، الرياضيات، العلوم، والمزيد",
    "courses.filter_all": "الكل",
    "courses.free": "مجاني",
    "courses.paid": "مدفوع",
    "courses.enroll": "التسجيل",
    "courses.currency": "د.ع",
    "courses.buy": "شراء الدورة",
    "courses.no_courses": "لم يتم العثور على دورات",
    "courses.what_you_learn": "ما ستتعلمه",
    "courses.lessons": "درس",
    "courses.instructor": "المدرس",
    "courses.not_found": "الدورة غير موجودة",
    "courses.back_to_home": "العودة للصفحة الرئيسية",
    "courses.created_by": "أنشئت بواسطة",
    "courses.one_time_payment": "دفعة واحدة",
    "courses.continue_learning": "واصل التعلم",
    "courses.enrolling": "جاري التسجيل...",
    "courses.enroll_free": "سجّل مجاناً",
    "courses.share_course": "مشاركة الدورة",
    "courses.buy_whatsapp": "اشترِ عبر واتساب",
    "courses.price_discount": "خصم",
    "courses.original_price": "السعر الأصلي",
    "courses.discounted_price": "السعر بعد الخصم",
    "courses.installment_available": "الدفع بالتقسيط متاح",
    "courses.limited_offer": "عرض محدود",
    "courses.already_applied": "تم طلب الشراء",
    "courses.sign_in_to_enroll": "الرجاء تسجيل الدخول للشراء",
    "courses.course_content": "محتوى الدورة",
    "courses.lesson_label": "الدرس",
    "courses.min": "دقيقة",
    "courses.watch": "مشاهدة",
    "courses.no_lessons": "لا توجد دروس متاحة بعد",
    "courses.your_instructor": "معلمك",
    "courses.unknown": "غير معروف",
    "courses.whatsapp_message": "مرحباً! أود التسجيل في \"{title}\" ({price})",
    "courses.search_placeholder": "ابحث عن الدورات...",
    "courses.course_found": "دورة",
    "courses.courses_found": "دورات",
    "courses.clear_search": "مسح البحث",
    "courses.view_details": "عرض التفاصيل",
    
    // Lesson
    "lesson.not_found": "الدرس غير موجود",
    "lesson.back_to_course": "العودة للدورة",
    "lesson.no_video": "لا يوجد فيديو متاح",
    
    // Comments/Q&A
    "comment.ask_question": "اطرح سؤالاً",
    "comment.ask_placeholder": "اسأل معلمك سؤالاً عن هذا الدرس...",
    "comment.post_question": "انشر السؤال",
    "comment.posting": "جاري النشر...",
    "comment.no_questions": "لا توجد أسئلة بعد. كن أول من يسأل!",
    "comment.teacher_badge": "معلم",
    "comment.reply": "رد",
    "comment.post_reply": "انشر الرد",
    "comment.reply_placeholder": "اكتب ردك...",
    "comment.cancel": "إلغاء",
    
    // User Roles
    "role.student": "طالب",
    "role.teacher": "معلم",
    "role.superadmin": "مدير النظام",
    
    // Toast Messages
    "toast.enrollment_success": "نجح التسجيل",
    "toast.enrollment_success_desc": "يمكنك الآن الوصول إلى محتوى الدورة",
    "toast.enrollment_pending": "تسجيل قيد الانتظار",
    "toast.enrollment_pending_desc": "سيتم تأكيد تسجيلك بعد إتمام الدفع عبر واتساب",
    "toast.enrollment_failed": "فشل التسجيل",
    "toast.popup_blocked": "تم حظر النافذة المنبثقة",
    "toast.popup_blocked_desc": "يرجى السماح بالنوافذ المنبثقة لهذا الموقع والمحاولة مرة أخرى",
    "toast.lesson_added": "تمت إضافة الدرس",
    "toast.lesson_added_desc": "تم إضافة الدرس الجديد بنجاح",
    "toast.lesson_updated": "تم تحديث الدرس",
    "toast.lesson_updated_desc": "تم تحديث الدرس بنجاح",
    "toast.lesson_deleted": "تم حذف الدرس",
    "toast.lesson_deleted_desc": "تم حذف الدرس بنجاح",
    "toast.quiz_created": "تم إنشاء الاختبار",
    "toast.quiz_created_desc": "تم إنشاء الاختبار الجديد بنجاح",
    "toast.quiz_updated": "تم تحديث الاختبار",
    "toast.quiz_updated_desc": "تم تحديث الاختبار بنجاح",
    "toast.quiz_deleted": "تم حذف الاختبار",
    "toast.quiz_deleted_desc": "تم حذف الاختبار بنجاح",
    "toast.course_updated": "تم تحديث الدورة",
    "toast.course_updated_desc": "تم تحديث الدورة بنجاح",
    "toast.course_deleted": "تم حذف الدورة",
    "toast.course_deleted_desc": "تم حذف الدورة بنجاح",
    "toast.failed": "فشل",
    "toast.lesson_completed": "اكتمل الدرس!",
    "toast.lesson_completed_desc": "عمل رائع! واصل التعلم.",
    "toast.question_posted": "تم نشر السؤال",
    "toast.question_posted_desc": "سيرد معلمك قريباً",
    "toast.question_failed": "فشل نشر السؤال",
    "toast.reply_posted": "تم نشر الرد",
    "toast.reply_posted_desc": "تم نشر ردك بنجاح",
    "toast.reply_failed": "فشل نشر الرد",
    "toast.error_generic": "حدث خطأ ما",
    "toast.course_created": "تم إنشاء الدورة بنجاح",
    "toast.course_created_desc": "يمكنك الآن إضافة دروس لدورتك",
    "toast.course_create_failed": "فشل إنشاء الدورة",
    "toast.validation_error": "خطأ في التحقق",
    "toast.fill_required_fields": "يرجى ملء جميع الحقول المطلوبة",
    "toast.enter_valid_price": "يرجى إدخال سعر صالح أو تحديد الدورة كمجانية",
    "toast.enrollment_confirmed": "تم تأكيد التسجيل",
    "toast.enrollment_confirmed_desc": "يمكن للطالب الآن الوصول إلى الدورة",
    "toast.category_created": "تم إنشاء الفئة بنجاح",
    "toast.category_created_desc": "يمكن الآن استخدام الفئة الجديدة في الدورات",
    "toast.category_updated": "تم تحديث الفئة بنجاح",
    "toast.category_updated_desc": "تم حفظ التغييرات على الفئة",
    "toast.category_deleted": "تم حذف الفئة بنجاح",
    "toast.category_deleted_desc": "تمت إزالة الفئة من المنصة",
    "toast.category_name_required": "اسم الفئة مطلوب",
    "toast.enrollment_update_failed": "فشل تحديث التسجيل",
    "toast.quiz_submitted": "تم إرسال الاختبار",
    "toast.quiz_submitted_desc": "سيقوم معلمك بتقييم إجاباتك قريباً",
    "toast.quiz_failed": "فشل إرسال الاختبار",
    "toast.too_many_images": "عدد كبير جداً من الصور",
    "toast.no_images": "لا توجد صور",
    "toast.link_copied": "تم نسخ الرابط",
    "toast.link_copied_desc": "تم نسخ رابط الدورة إلى الحافظة",
    
    // Quiz
    "quiz.quizzes": "الاختبارات",
    "quiz.upload_solution": "ارفع الحل (صور)",
    "quiz.images_selected": "صور محددة",
    
    // Auth
    "auth.login": "تسجيل الدخول",
    "auth.register": "إنشاء حساب",
    "auth.email": "البريد الإلكتروني",
    "auth.password": "كلمة المرور",
    "auth.full_name": "الاسم الكامل",
    "auth.create_account": "إنشاء حساب",
    "auth.no_account": "ليس لديك حساب؟",
    "auth.have_account": "لديك حساب؟",
    "auth.welcome_back": "مرحباً بعودتك",
    "auth.enter_credentials": "أدخل بياناتك للوصول إلى حسابك",
    "auth.signing_in": "جاري تسجيل الدخول...",
    "auth.back_to_home": "→ العودة للصفحة الرئيسية",
    "auth.invalid_email": "عنوان البريد الإلكتروني غير صالح",
    "auth.password_required": "كلمة المرور مطلوبة",
    "auth.email_placeholder": "your.email@example.com",
    "auth.password_placeholder": "أدخل كلمة المرور",
    "auth.fullname_placeholder": "علي محمد",
    "auth.new_password": "كلمة المرور الجديدة",
    "auth.confirm_password": "تأكيد كلمة المرور",
    "auth.confirm_password_placeholder": "أعد إدخال كلمة المرور",
    "auth.passwords_must_match": "كلمات المرور يجب أن تتطابق",
    "auth.password_min_length": "كلمة المرور يجب أن تكون 6 أحرف على الأقل",
    "auth.fullname_min_length": "الاسم يجب أن يكون حرفين على الأقل",
    "auth.whatsapp_number": "رقم الواتساب",
    "auth.whatsapp_placeholder": "+9467730145334",
    "auth.phone_min_length": "رقم الواتساب يجب أن يكون 10 أرقام على الأقل",
    "auth.reset_password_desc": "أدخل بريدك الإلكتروني لتلقي رابط إعادة تعيين كلمة المرور",
    "auth.reset_email_sent_desc": "لقد أرسلنا لك رابط إعادة تعيين كلمة المرور",
    "auth.check_email_instructions": "تحقق من بريدك الإلكتروني للحصول على تعليمات إعادة تعيين كلمة المرور",
    "auth.enter_new_password": "أدخل كلمة المرور الجديدة",
    "auth.invalid_reset_link": "رابط إعادة التعيين غير صالح",
    "auth.invalid_reset_link_desc": "رابط إعادة تعيين كلمة المرور غير صالح أو منتهي الصلاحية",
    "auth.password_reset_success": "تم إعادة تعيين كلمة المرور بنجاح",
    "auth.password_reset_success_desc": "يمكنك الآن تسجيل الدخول بكلمة المرور الجديدة",
    
    // Register
    "register.subtitle": "انضم إلى آلاف المتعلمين في منصة ابراج التعليمية",
    "register.creating_account": "جاري إنشاء الحساب...",
    
    // Login/Register Toast Messages
    "toast.login_success": "تم تسجيل الدخول بنجاح",
    "toast.login_success_desc": "مرحباً بعودتك!",
    "toast.login_failed": "فشل تسجيل الدخول",
    "toast.login_failed_desc": "البريد الإلكتروني أو كلمة المرور غير صحيحة",
    "toast.register_success": "تم التسجيل بنجاح",
    "toast.register_success_desc": "مرحباً بك في",
    "toast.register_failed": "فشل التسجيل",
    "toast.register_failed_desc": "حدث خطأ ما",
    "toast.reset_request_sent": "تم إرسال طلب إعادة التعيين",
    "toast.reset_request_sent_desc": "تحقق من بريدك الإلكتروني للحصول على التعليمات",
    "toast.reset_request_failed": "فشل طلب إعادة التعيين",
    "toast.reset_request_failed_desc": "حدث خطأ أثناء معالجة طلبك",
    "toast.password_reset_success": "تم إعادة تعيين كلمة المرور",
    "toast.password_reset_success_desc": "يمكنك الآن تسجيل الدخول بكلمة المرور الجديدة",
    "toast.password_reset_failed": "فشل إعادة تعيين كلمة المرور",
    "toast.password_reset_failed_desc": "رابط إعادة التعيين غير صالح أو منتهي الصلاحية",
    
    // Dashboard - Superadmin
    "dashboard.superadmin.title": "لوحة تحكم المسؤول",
    "dashboard.superadmin.subtitle": "إدارة مستخدمي المنصة ومراقبة الإحصائيات",
    "dashboard.superadmin.total_teachers": "إجمالي المعلمين",
    "dashboard.superadmin.total_students": "إجمالي الطلاب",
    "dashboard.superadmin.total_courses": "إجمالي الدورات",
    "dashboard.superadmin.total_enrollments": "إجمالي التسجيلات",
    "dashboard.superadmin.teachers": "المعلمون",
    "dashboard.superadmin.manage_teachers": "إدارة حسابات المعلمين",
    "dashboard.superadmin.create_teacher": "إنشاء معلم",
    "dashboard.superadmin.students": "الطلاب",
    "dashboard.superadmin.manage_students": "إدارة حسابات الطلاب",
    "dashboard.superadmin.name": "الاسم",
    "dashboard.superadmin.email": "البريد الإلكتروني",
    "dashboard.superadmin.status": "الحالة",
    "dashboard.superadmin.active": "نشط",
    "dashboard.superadmin.no_teachers": "لم يتم العثور على معلمين",
    "dashboard.superadmin.no_students": "لم يتم العثور على طلاب",
    "dashboard.superadmin.pending_enrollments": "التسجيلات المعلقة",
    "dashboard.superadmin.pending_enrollments_desc": "إدارة طلبات التسجيل المعلقة للدورات المدفوعة",
    "dashboard.superadmin.no_pending_enrollments": "لا توجد تسجيلات معلقة",
    "dashboard.superadmin.categories": "الفئات",
    "dashboard.superadmin.manage_categories": "إدارة فئات الدورات",
    "dashboard.superadmin.create_category": "إنشاء فئة",
    "dashboard.superadmin.no_categories": "لم يتم العثور على فئات",
    "dashboard.superadmin.course_stats": "إحصائيات الدورات",
    "dashboard.superadmin.course_stats_desc": "عرض تفصيلي لجميع الدورات وعدد الطلاب",
    "dashboard.superadmin.no_courses": "لم يتم العثور على دورات",
    "dashboard.superadmin.teacher_stats": "إحصائيات المعلمين",
    "dashboard.superadmin.teacher_stats_desc": "عرض تفصيلي لجميع المعلمين ودوراتهم وطلابهم",
    
    // Dashboard - Teacher
    "dashboard.teacher.title": "لوحة تحكم المعلم",
    "dashboard.teacher.pending_approval": "بانتظار موافقة المسؤول",
    "dashboard.teacher.welcome": "مرحباً بعودتك",
    "dashboard.teacher.my_courses": "دوراتي",
    "dashboard.teacher.students": "الطلاب",
    "dashboard.teacher.total_enrollments": "إجمالي التسجيلات",
    "dashboard.teacher.create_course": "إنشاء دورة",
    "dashboard.teacher.manage_courses": "إدارة دوراتك",
    "dashboard.teacher.no_courses": "لم تنشئ أي دورات بعد",
    "dashboard.teacher.get_started": "ابدأ بإنشاء دورتك الأولى",
    "dashboard.teacher.pending_enrollments": "التسجيلات قيد الانتظار",
    "dashboard.teacher.pending_enrollments_desc": "تأكيد دفع الطلاب لفتح الوصول إلى الدورة",
    "dashboard.teacher.pending": "قيد الانتظار",
    "dashboard.teacher.all_enrollments": "جميع التسجيلات",
    "dashboard.teacher.all_enrollments_desc": "عرض جميع الطلاب المسجلين في دوراتك",
    "dashboard.teacher.view_enrollments": "عرض التسجيلات",
    "dashboard.teacher.filter_all": "الكل",
    "dashboard.teacher.filter_confirmed": "مؤكد",
    "dashboard.teacher.filter_pending": "قيد الانتظار",
    "dashboard.teacher.filter_free": "مجاني",
    "dashboard.teacher.enrollment_status": "الحالة",
    "dashboard.teacher.student_phone": "رقم الطالب",
    "dashboard.teacher.no_enrollments": "لا توجد تسجيلات بعد",
    "dashboard.teacher.no_enrollments_desc": "سيظهر الطلاب المسجلون في دوراتك هنا",
    "dashboard.teacher.course": "الدورة",
    
    // Dashboard - Student
    "dashboard.student.title": "لوحة تحكم الطالب",
    "dashboard.student.welcome": "مرحباً بعودتك",
    "dashboard.student.continue": "واصل رحلتك التعليمية",
    "dashboard.student.enrolled_courses": "الدورات المسجلة",
    "dashboard.student.completed": "مكتملة",
    "dashboard.student.avg_progress": "متوسط التقدم",
    "dashboard.student.my_courses": "دوراتي",
    "dashboard.student.continue_learning": "واصل التعلم",
    "dashboard.student.progress": "التقدم",
    "dashboard.student.resume": "استئناف",
    "dashboard.student.no_courses": "لم تسجل في أي دورات بعد",
    "dashboard.student.explore": "استكشف دوراتنا وابدأ التعلم اليوم",
    
    // Create Teacher Dialog
    "dialog.create_teacher.title": "إنشاء حساب معلم",
    "dialog.create_teacher.description": "إنشاء حساب معلم جديد. سيتم إنشاء كلمة مرور عشوائية.",
    "dialog.create_teacher.full_name": "الاسم الكامل",
    "dialog.create_teacher.email": "البريد الإلكتروني",
    "dialog.create_teacher.cancel": "إلغاء",
    "dialog.create_teacher.create": "إنشاء",
    "dialog.create_teacher.creating": "جاري الإنشاء...",
    "dialog.create_teacher.success": "تم إنشاء المعلم بنجاح!",
    "dialog.create_teacher.password_label": "كلمة المرور المولدة",
    "dialog.create_teacher.password_note": "يرجى حفظ كلمة المرور هذه ومشاركتها مع المعلم. لن تظهر مرة أخرى.",
    "dialog.create_teacher.copy_password": "نسخ كلمة المرور",
    "dialog.create_teacher.password_copied": "تم نسخ كلمة المرور!",
    "dialog.create_teacher.password_copied_desc": "تم نسخ كلمة المرور إلى الحافظة",
    "dialog.create_teacher.failed": "فشل إنشاء المعلم",
    "dialog.create_teacher.validation_error": "خطأ في التحقق",
    "dialog.create_teacher.fill_all_fields": "يرجى ملء جميع الحقول",
    
    // Delete Confirmation
    "dialog.delete.title": "تأكيد الحذف",
    "dialog.delete.teacher_message": "هل أنت متأكد من حذف هذا المعلم؟ هذا الإجراء لا يمكن التراجع عنه.",
    "dialog.delete.student_message": "هل أنت متأكد من حذف هذا الطالب؟ هذا الإجراء لا يمكن التراجع عنه.",
    "dialog.delete.category_message": "هل أنت متأكد من حذف هذه الفئة؟ لا يمكن حذف الفئات التي تحتوي على دورات.",
    "dialog.delete.confirm": "نعم، احذف",
    "dialog.delete.cancel": "إلغاء",
    "dialog.delete.deleting": "جاري الحذف...",
    "dialog.delete.teacher_success": "تم حذف المعلم بنجاح",
    "dialog.delete.teacher_success_desc": "تم حذف حساب المعلم من المنصة",
    "dialog.delete.student_success": "تم حذف الطالب بنجاح",
    "dialog.delete.student_success_desc": "تم حذف حساب الطالب من المنصة",
    "dialog.delete.failed": "فشل الحذف",
    
    // Category Dialog
    "dialog.category.create_title": "إنشاء فئة جديدة",
    "dialog.category.create_description": "أنشئ فئة جديدة لتنظيم الدورات",
    "dialog.category.edit_title": "تعديل الفئة",
    "dialog.category.edit_description": "تحديث معلومات الفئة",
    "dialog.category.name": "اسم الفئة",
    "dialog.category.name_placeholder": "مثال: البرمجة، الرياضيات، العلوم",
    "dialog.category.description": "الوصف",
    "dialog.category.description_placeholder": "وصف قصير للفئة (اختياري)",
    "dialog.category.create": "إنشاء",
    "dialog.category.update": "تحديث",
    "dialog.category.saving": "جاري الحفظ...",
    
    // Reset Password Dialog
    "dialog.reset_password.title": "إعادة تعيين كلمة مرور المعلم",
    "dialog.reset_password.description": "أدخل كلمة مرور جديدة لحساب المعلم",
    
    // Common Actions
    "action.view": "عرض",
    "action.edit": "تعديل",
    "action.delete": "حذف",
    "action.save": "حفظ",
    "action.cancel": "إلغاء",
    "action.confirm_delete": "تأكيد الحذف",
    "action.edit_lesson": "تعديل الدرس",
    "action.edit_quiz": "تعديل الاختبار",
    "action.edit_course": "تعديل الدورة",
    "confirm.delete_lesson": "هل أنت متأكد من حذف هذا الدرس؟",
    "confirm.delete_quiz": "هل أنت متأكد من حذف هذا الاختبار؟",
    "confirm.delete_course": "هل أنت متأكد من حذف هذه الدورة؟ سيتم حذف جميع الدروس والاختبارات المرتبطة بها.",
    "confirm.delete_warning": "هذا الإجراء لا يمكن التراجع عنه.",
    "action.submit": "إرسال",
    "action.back": "رجوع",
    "action.next": "التالي",
    "action.close": "إغلاق",
    "action.add_lesson": "إضافة درس",
    "action.add_quiz": "إضافة اختبار",
    "action.view_public": "عرض الصفحة العامة",
    "action.confirm": "تأكيد",
    "action.send_reset_link": "إرسال رابط إعادة التعيين",
    "action.sending": "جاري الإرسال...",
    "action.back_to_login": "العودة لتسجيل الدخول",
    "action.reset_password": "إعادة تعيين كلمة المرور",
    "action.resetting": "جاري إعادة التعيين...",
    "action.request_new_link": "طلب رابط جديد",
    "action.go_to_login": "الذهاب لتسجيل الدخول",
    
    // Button Labels
    "button.confirm": "تأكيد",
    
    // Manage Course
    "manage.lessons_desc": "إدارة دروس الدورة وإضافة محتوى جديد",
    "manage.no_lessons": "لا توجد دروس بعد. أضف درسك الأول!",
    "manage.quizzes": "الاختبارات",
    "manage.no_quizzes": "لا توجد اختبارات لهذا الدرس حتى الآن.",
    "manage.update_course_info": "حدّث معلومات الدورة مثل العنوان والسعر",
    
    // Form Labels
    "label.course_title": "عنوان الدورة",
    "label.lesson_title": "عنوان الدرس",
    "label.youtube_url": "رابط يوتيوب",
    "label.duration_minutes": "المدة (بالدقائق)",
    "label.lesson_order": "الترتيب",
    "label.minutes": "دقيقة",
    "label.quiz_title": "عنوان الاختبار",
    "label.quiz_description": "وصف الاختبار",
    "label.deadline": "الموعد النهائي",
    "label.category": "الفئة",
    "label.description": "الوصف",
    "label.price": "السعر",
    "label.course_thumbnail": "صورة الدورة",
    "label.email": "البريد الإلكتروني",
    "label.new_password": "كلمة المرور الجديدة",
    "label.confirm_password": "تأكيد كلمة المرور",
    "label.student": "الطالب",
    "label.course": "الدورة",
    "label.teacher": "المعلم",
    "label.enrolled_at": "تاريخ التسجيل",
    "label.actions": "الإجراءات",
    "label.no_description": "لا يوجد وصف",
    "label.lessons": "الدروس",
    "label.total_students": "إجمالي الطلاب",
    "label.total_lessons": "إجمالي الدروس",
    "label.confirmed": "مؤكد",
    "label.pending": "قيد الانتظار",
    "label.free": "مجاني",
    "label.courses": "الدورات",
    "label.whatsapp": "واتساب",
    "label.course_details": "تفاصيل الدورات",
    "label.students": "الطلاب",
    
    // Placeholders
    "placeholder.lesson_title": "مثال: مقدمة في البرمجة",
    "placeholder.quiz_title": "مثال: اختبار الوحدة 1",
    "placeholder.quiz_description": "أجب عن الأسئلة التالية...",
    
    // Placeholders
    "placeholder.course_title": "مقدمة في تطوير الويب",
    "placeholder.course_description": "دورة شاملة تغطي...",
    "placeholder.what_you_learn": "بناء تطبيقات الويب\nفهم JavaScript\nالعمل مع واجهات برمجة التطبيقات",
    "placeholder.price": "25000",
    
    // Categories
    "category.programming": "البرمجة",
    "category.mathematics": "الرياضيات",
    "category.science": "العلوم",
    "category.languages": "اللغات",
    "category.business": "الأعمال",
    "category.design": "التصميم",
    
    // Status
    "status.pending": "قيد الانتظار",
    "status.confirmed": "مؤكد",
    "status.active": "نشط",
    "status.inactive": "غير نشط",
    
    // Admin & User Management
    "admin.manage_teachers": "إدارة المعلمين",
    "admin.manage_students": "إدارة الطلاب",
    "admin.manage_enrollments": "إدارة التسجيلات",
    "admin.platform_analytics": "تحليلات المنصة",
    "admin.create_teacher": "إنشاء حساب معلم",
    "admin.full_name": "الاسم الكامل",
    "admin.password": "كلمة المرور",
    "admin.creating": "جاري الإنشاء...",
    "admin.teacher_created": "تم إنشاء حساب المعلم بنجاح",
    "admin.no_teachers": "لا يوجد معلمون حتى الآن",
    "admin.no_students": "لا يوجد طلاب حتى الآن",
    "admin.no_enrollments": "لا توجد تسجيلات حتى الآن",
    "admin.filter_all": "الكل",
    "admin.filter_pending": "قيد الانتظار",
    "admin.filter_confirmed": "مؤكدة",
    "admin.approve": "موافقة",
    "admin.updating": "جاري التحديث...",
    "admin.total_courses": "إجمالي الدورات",
    "admin.total_students": "إجمالي الطلاب",
    "admin.total_teachers": "إجمالي المعلمين",
    "admin.total_enrollments": "إجمالي التسجيلات",
    "admin.course_analytics": "تحليلات الدورات",
    "admin.teacher_analytics": "تحليلات المعلمين",
    "admin.enrollment_breakdown": "تفصيل التسجيلات",
    
    // Dashboard
    "dashboard.welcome": "مرحباً",
    "dashboard.my_courses": "دوراتي",
    "dashboard.my_enrollments": "تسجيلاتي",
    "dashboard.create_course": "إنشاء دورة جديدة",
    "dashboard.manage_course": "إدارة الدورة",
    "dashboard.edit_course": "تحرير الدورة",
    "dashboard.view_details": "عرض التفاصيل",
    "dashboard.no_courses": "لم تُنشئ أي دورات بعد",
    "dashboard.no_enrollments": "لم تسجل في أي دورات بعد",
    "dashboard.progress": "التقدم",
    "dashboard.continue": "متابعة",
    "dashboard.enrollment_pending": "تسجيلك قيد المراجعة. سنرسل إليك إشعاراً بمجرد التأكيد.",
    "dashboard.contact_whatsapp": "اتصل عبر واتساب",
    "dashboard.pending_status": "قيد الانتظار",
    
    // Course Details & Reviews
    "course.reviews": "التقييمات والمراجعات",
    "course.no_reviews": "لا توجد مراجعات بعد",
    "course.write_review": "اكتب مراجعة",
    "course.edit_review": "تحرير المراجعة",
    "course.your_rating": "تقييمك",
    "course.your_review": "مراجعتك",
    "course.submit_review": "إرسال المراجعة",
    "course.update_review": "تحديث المراجعة",
    "course.delete_review": "حذف المراجعة",
    "course.confirm_delete_review": "هل أنت متأكد أنك تريد حذف مراجعتك؟",
    "course.announcements": "الإعلانات",
    "course.no_announcements": "لا توجد إعلانات",
    "course.new_announcement": "إعلان جديد",
    "course.announcement_title": "عنوان الإعلان",
    "course.announcement_content": "محتوى الإعلان",
    "course.post_announcement": "نشر الإعلان",
    "course.posted": "تم النشر",
    
    // Quiz & Submissions
    "quiz.available_quizzes": "الاختبارات المتاحة",
    "quiz.no_quizzes": "لا توجد اختبارات متاحة",
    "quiz.deadline": "الموعد النهائي",
    "quiz.submit_solution": "إرسال الحل",
    "quiz.upload_image": "رفع صورة الحل",
    "quiz.submit": "إرسال",
    "quiz.submitting": "جاري الإرسال...",
    "quiz.your_submissions": "إرسالاتك",
    "quiz.no_submissions": "لم تُرسل أي حلول بعد",
    "quiz.submitted_at": "تاريخ الإرسال",
    "quiz.score": "الدرجة",
    "quiz.feedback": "الملاحظات",
    "quiz.pending_grade": "قيد التقييم",
    "quiz.view_submission": "عرض الإرسال",
    "quiz.grade_submission": "تقييم الإرسال",
    "quiz.enter_score": "أدخل الدرجة",
    "quiz.enter_feedback": "أدخل الملاحظات",
    "quiz.save_grade": "حفظ التقييم",
    
    // Comments & Q&A
    "comments.ask_question": "اطرح سؤالاً",
    "comments.your_question": "سؤالك",
    "comments.post_question": "نشر السؤال",
    "comments.no_questions": "لا توجد أسئلة بعد. كن أول من يسأل!",
    "comments.reply": "رد",
    "comments.teacher_reply": "رد المعلم",
    "comments.post_reply": "نشر الرد",
    
    // Lesson Player
    "lesson.previous": "السابق",
    "lesson.next": "التالي",
    "lesson.previous_lesson": "الدرس السابق",
    "lesson.next_lesson": "الدرس التالي",
    "lesson.of": "من",
    "lesson.mark_complete": "وضع علامة كمكتمل",
    "lesson.completed": "مكتمل",
    "lesson.marking": "جاری الحفظ...",
    "lesson.no_next": "لا يوجد درس تالي",
    "lesson.no_previous": "لا يوجد درس سابق",
    
    // Authentication
    "auth.sign_in": "تسجيل الدخول",
    "auth.sign_up": "إنشاء حساب",
    "auth.forgot_password": "نسيت كلمة المرور؟",
    "auth.forgot_password_contact": "نسيت كلمة المرور؟ تواصل معنا عبر واتساب:",
    "auth.contact_whatsapp": "تواصل عبر واتساب",
    "auth.reset_password": "إعادة تعيين كلمة المرور",
    "auth.send_reset_link": "إرسال رابط الاستعادة",
    "auth.back_to_login": "العودة لتسجيل الدخول",
    "auth.email_sent": "تم إرسال رابط إعادة التعيين إلى بريدك الإلكتروني",
    "auth.reset_success": "تم تحديث كلمة المرور بنجاح",
    "auth.student_account": "حساب طالب",
    
    // Messages & Errors
    "error.failed_load": "فشل في تحميل البيانات",
    "error.failed_create": "فشل في الإنشاء",
    "error.failed_update": "فشل في التحديث",
    "error.failed_delete": "فشل في الحذف",
    "success.created": "تم الإنشاء بنجاح",
    "success.updated": "تم التحديث بنجاح",
    "success.deleted": "تم الحذف بنجاح",
    
    // Footer
    "footer.tagline": "حوّل مستقبلك مع دورات الخبراء عبر الإنترنت",
    "footer.platform": "المنصة",
    "footer.about": "من نحن",
    "footer.how_it_works": "كيف يعمل",
    "footer.careers": "الوظائف",
    "footer.blog": "المدونة",
    "footer.courses": "الدورات",
    "footer.browse_courses": "تصفح الدورات",
    "footer.become_teacher": "كن معلماً",
    "footer.become_teacher_message": "مرحباً، أرغب في أن أصبح معلماً على منصة ابراج التعليمية",
    "footer.pricing": "الأسعار",
    "footer.support": "الدعم",
    "footer.help_center": "مركز المساعدة",
    "footer.contact_us": "اتصل بنا",
    "footer.privacy": "سياسة الخصوصية",
    "footer.terms": "شروط الخدمة",
    "footer.copyright": "© جميع الحقوق محفوظة.",
    
    // About Us Page
    "about.title": "من نحن",
    "about.subtitle": "منصة تعليمية رائدة تهدف إلى تمكين المتعلمين في جميع أنحاء العالم",
    "about.mission_title": "مهمتنا",
    "about.mission_desc": "نسعى لتوفير تعليم عالي الجودة يمكن الوصول إليه للجميع. نؤمن بأن التعليم هو مفتاح النجاح، ونعمل على توفير بيئة تعليمية متميزة تجمع بين أفضل المعلمين والطلاب المتحمسين للتعلم.",
    "about.vision_title": "رؤيتنا",
    "about.vision_desc": "نطمح لأن نكون المنصة التعليمية الأولى في المنطقة، حيث يمكن لكل شخص الوصول إلى تعليم متميز يساعده على تحقيق أهدافه المهنية والشخصية. نسعى لبناء مجتمع تعليمي نابض بالحياة يدعم التعلم المستمر والتطوير الذاتي.",
    "about.features_title": "لماذا تختار منصة ابراج التعليمية؟",
    "about.feature_quality_title": "محتوى عالي الجودة",
    "about.feature_quality_desc": "دورات مصممة بعناية من قبل خبراء في مجالاتهم",
    "about.feature_teachers_title": "معلمون محترفون",
    "about.feature_teachers_desc": "تعلم من أفضل المعلمين ذوي الخبرة الواسعة",
    "about.feature_courses_title": "تنوع في المحتوى",
    "about.feature_courses_desc": "مجموعة واسعة من الدورات في مختلف المجالات",
    "about.feature_progress_title": "تتبع التقدم",
    "about.feature_progress_desc": "راقب تقدمك وحقق أهدافك التعليمية",
  },
  en: {
    // Common
    "common.loading": "Loading...",
    "common.welcome": "Welcome to",
    "app.name": "Abraj Educational Platform",
    "app.tagline": "Electronic Learning Platform",
    "app.description": "Electronic Learning Platform",
    
    // Navigation
    "nav.browse": "Browse Courses",
    "nav.my_learning": "My Learning",
    "nav.dashboard": "Dashboard",
    "nav.sign_in": "Sign in",
    "nav.get_started": "Get started",
    "nav.logout": "Log out",
    
    // Notifications
    "notifications.title": "Notifications",
    "notifications.unread": "unread",
    "notifications.no_notifications": "No notifications",
    
    // Home Page
    "home.hero_title": "Abraj Educational Platform",
    "home.hero_subtitle": "Electronic Learning Platform",
    "home.get_started": "Get Started Free",
    "home.browse_courses": "Browse Courses",
    "home.stats.courses": "Courses",
    "home.stats.students": "Students",
    "home.stats.teachers": "Expert Teachers",
    "home.stats.rating": "Average Rating",
    "home.featured_courses": "Featured Courses",
    "home.view_all": "View All",
    "home.how_it_works": "How It Works",
    "home.step1.title": "Browse Courses",
    "home.step1.description": "Explore our catalog of courses across various categories",
    "home.step2.title": "Enroll & Learn",
    "home.step2.description": "Contact us via WhatsApp to enroll in paid courses or start learning immediately with free courses",
    "home.step3.title": "Achieve Goals",
    "home.step3.description": "Complete quizzes, track progress, and master new skills",
    "home.view_course": "View Course",
    "home.no_courses_category": "No courses in this category. Try another category.",
    "home.no_courses_available": "No courses available yet. Check back soon!",
    
    // Courses
    "courses.title": "Explore Our Courses",
    "courses.subtitle": "Discover courses in programming, mathematics, science, and more",
    "courses.filter_all": "All",
    "courses.free": "Free",
    "courses.paid": "Paid",
    "courses.enroll": "Enroll",
    "courses.currency": "iqd",
    "courses.buy": "Buy Course",
    "courses.no_courses": "No courses found",
    "courses.what_you_learn": "What you'll learn",
    "courses.lessons": "Lessons",
    "courses.instructor": "Instructor",
    "courses.not_found": "Course not found",
    "courses.back_to_home": "Back to Home",
    "courses.created_by": "Created by",
    "courses.one_time_payment": "One-time payment",
    "courses.continue_learning": "Continue Learning",
    "courses.enrolling": "Enrolling...",
    "courses.enroll_free": "Enroll for Free",
    "courses.share_course": "Share Course",
    "courses.buy_whatsapp": "Buy via WhatsApp",
    "courses.price_discount": "Discount",
    "courses.original_price": "Original Price",
    "courses.discounted_price": "Discounted Price",
    "courses.installment_available": "Installment Available",
    "courses.limited_offer": "Limited Offer",
    "courses.already_applied": "Already Applied",
    "courses.sign_in_to_enroll": "Please sign in to purchase",
    "courses.course_content": "Course Content",
    "courses.lesson_label": "Lesson",
    "courses.min": "min",
    "courses.watch": "Watch",
    "courses.no_lessons": "No lessons available yet",
    "courses.your_instructor": "Your Instructor",
    "courses.unknown": "Unknown",
    "courses.whatsapp_message": "Hi! I would like to enroll in \"{title}\" ({price})",
    "courses.search_placeholder": "Search for courses...",
    "courses.course_found": "course",
    "courses.courses_found": "courses",
    "courses.clear_search": "Clear Search",
    "courses.view_details": "View Details",
    
    // Lesson
    "lesson.not_found": "Lesson not found",
    "lesson.back_to_course": "Back to Course",
    "lesson.no_video": "No video available",
    "lesson.previous": "Previous",
    "lesson.mark_complete": "Mark as Complete",
    
    // Comments/Q&A
    "comment.ask_question": "Ask a Question",
    "comment.ask_placeholder": "Ask your teacher a question about this lesson...",
    "comment.post_question": "Post Question",
    "comment.posting": "Posting...",
    "comment.no_questions": "No questions yet. Be the first to ask!",
    "comment.teacher_badge": "Teacher",
    "comment.reply": "Reply",
    "comment.post_reply": "Post Reply",
    "comment.reply_placeholder": "Write your reply...",
    "comment.cancel": "Cancel",
    
    // User Roles
    "role.student": "Student",
    "role.teacher": "Teacher",
    "role.superadmin": "Super Admin",
    
    // Toast Messages
    "toast.enrollment_success": "Enrollment successful",
    "toast.enrollment_success_desc": "You can now access the course content",
    "toast.enrollment_pending": "Enrollment pending",
    "toast.enrollment_pending_desc": "Your enrollment will be confirmed after payment via WhatsApp",
    "toast.enrollment_failed": "Enrollment failed",
    "toast.popup_blocked": "Popup blocked",
    "toast.popup_blocked_desc": "Please allow popups for this site and try again",
    "toast.lesson_added": "Lesson added",
    "toast.lesson_added_desc": "New lesson added successfully",
    "toast.lesson_updated": "Lesson updated",
    "toast.lesson_updated_desc": "Lesson updated successfully",
    "toast.lesson_deleted": "Lesson deleted",
    "toast.lesson_deleted_desc": "Lesson deleted successfully",
    "toast.quiz_created": "Quiz created",
    "toast.quiz_created_desc": "New quiz created successfully",
    "toast.quiz_updated": "Quiz updated",
    "toast.quiz_updated_desc": "Quiz updated successfully",
    "toast.quiz_deleted": "Quiz deleted",
    "toast.quiz_deleted_desc": "Quiz deleted successfully",
    "toast.course_updated": "Course updated",
    "toast.course_updated_desc": "Course updated successfully",
    "toast.course_deleted": "Course deleted",
    "toast.course_deleted_desc": "Course deleted successfully",
    "toast.failed": "Failed",
    "toast.lesson_completed": "Lesson completed!",
    "toast.lesson_completed_desc": "Great job! Keep learning.",
    "toast.question_posted": "Question posted",
    "toast.question_posted_desc": "Your teacher will respond soon",
    "toast.question_failed": "Failed to post question",
    "toast.reply_posted": "Reply posted",
    "toast.reply_posted_desc": "Your reply has been posted successfully",
    "toast.reply_failed": "Failed to post reply",
    "toast.error_generic": "Something went wrong",
    "toast.course_created": "Course created successfully",
    "toast.course_created_desc": "You can now add lessons to your course",
    "toast.course_create_failed": "Failed to create course",
    "toast.validation_error": "Validation error",
    "toast.fill_required_fields": "Please fill in all required fields",
    "toast.enter_valid_price": "Please enter a valid price or mark the course as free",
    "toast.enrollment_confirmed": "Enrollment confirmed",
    "toast.enrollment_confirmed_desc": "Student can now access the course",
    "toast.category_created": "Category created successfully",
    "toast.category_created_desc": "The new category can now be used for courses",
    "toast.category_updated": "Category updated successfully",
    "toast.category_updated_desc": "Category changes have been saved",
    "toast.category_deleted": "Category deleted successfully",
    "toast.category_deleted_desc": "The category has been removed from the platform",
    "toast.category_name_required": "Category name is required",
    "toast.password_reset_teacher_desc": "New password generated for teacher",
    "toast.password_reset_student_desc": "New password generated for student",
    "toast.enrollment_update_failed": "Failed to update enrollment",
    "toast.quiz_submitted": "Quiz submitted",
    "toast.quiz_submitted_desc": "Your teacher will grade your answers soon",
    "toast.quiz_failed": "Failed to submit quiz",
    "toast.too_many_images": "Too many images",
    "toast.no_images": "No images",
    "toast.link_copied": "Link Copied",
    "toast.link_copied_desc": "Course link copied to clipboard",
    
    // Quiz
    "quiz.quizzes": "Quizzes",
    "quiz.upload_solution": "Upload Solution (Images)",
    "quiz.images_selected": "images selected",
    "quiz.submit": "Submit Solution",
    "quiz.submitting": "Submitting...",
    "quiz.no_quizzes": "No quizzes for this lesson",
    
    // Auth
    "auth.login": "Login",
    "auth.register": "Register",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.full_name": "Full Name",
    "auth.sign_in": "Sign in",
    "auth.create_account": "Create Account",
    "auth.no_account": "Don't have an account?",
    "auth.have_account": "Already have an account?",
    "auth.welcome_back": "Welcome back",
    "auth.enter_credentials": "Enter your credentials to access your account",
    "auth.signing_in": "Signing in...",
    "auth.back_to_home": "← Back to home",
    "auth.invalid_email": "Invalid email address",
    "auth.password_required": "Password is required",
    "auth.email_placeholder": "your.email@example.com",
    "auth.password_placeholder": "Enter your password",
    "auth.fullname_placeholder": "Ali Mohammed",
    "auth.new_password": "New Password",
    "auth.confirm_password": "Confirm Password",
    "auth.confirm_password_placeholder": "Re-enter your password",
    "auth.passwords_must_match": "Passwords must match",
    "auth.password_min_length": "Password must be at least 6 characters",
    "auth.fullname_min_length": "Name must be at least 2 characters",
    "auth.whatsapp_number": "WhatsApp Number",
    "auth.whatsapp_placeholder": "+9467730145334",
    "auth.phone_min_length": "WhatsApp number must be at least 10 digits",
    "auth.reset_password": "Reset Password",
    "auth.reset_password_desc": "Enter your email to receive a password reset link",
    "auth.reset_email_sent_desc": "We've sent you a password reset link",
    "auth.check_email_instructions": "Check your email for password reset instructions",
    "auth.enter_new_password": "Enter your new password",
    "auth.invalid_reset_link": "Invalid Reset Link",
    "auth.invalid_reset_link_desc": "The password reset link is invalid or has expired",
    "auth.password_reset_success": "Password Reset Successful",
    "auth.password_reset_success_desc": "You can now login with your new password",
    "auth.forgot_password": "Forgot password?",
    "auth.forgot_password_contact": "Forgot password? Contact us on WhatsApp:",
    "auth.contact_whatsapp": "Contact on WhatsApp",
    
    // Register
    "register.subtitle": "Join thousands of learners on Abraj Educational Platform",
    "register.creating_account": "Creating account...",
    
    // Login/Register Toast Messages
    "toast.login_success": "Login successful",
    "toast.login_success_desc": "Welcome back!",
    "toast.login_failed": "Login failed",
    "toast.login_failed_desc": "Invalid email or password",
    "toast.register_success": "Registration successful",
    "toast.register_success_desc": "Welcome to",
    "toast.register_failed": "Registration failed",
    "toast.register_failed_desc": "Something went wrong",
    "toast.reset_request_sent": "Reset request sent",
    "toast.reset_request_sent_desc": "Check your email for instructions",
    "toast.reset_request_failed": "Reset request failed",
    "toast.reset_request_failed_desc": "An error occurred while processing your request",
    "toast.password_reset_success": "Password reset successful",
    "toast.password_reset_success_desc": "You can now login with your new password",
    "toast.password_reset_failed": "Password reset failed",
    "toast.password_reset_failed_desc": "The reset link is invalid or has expired",
    
    // Dashboard - Superadmin
    "dashboard.superadmin.title": "Superadmin Dashboard",
    "dashboard.superadmin.subtitle": "Manage platform users and monitor statistics",
    "dashboard.superadmin.total_teachers": "Total Teachers",
    "dashboard.superadmin.total_students": "Total Students",
    "dashboard.superadmin.total_courses": "Total Courses",
    "dashboard.superadmin.total_enrollments": "Total Enrollments",
    "dashboard.superadmin.teachers": "Teachers",
    "dashboard.superadmin.manage_teachers": "Manage teacher accounts",
    "dashboard.superadmin.create_teacher": "Create Teacher",
    "dashboard.superadmin.students": "Students",
    "dashboard.superadmin.manage_students": "Manage student accounts",
    "dashboard.superadmin.name": "Name",
    "dashboard.superadmin.email": "Email",
    "dashboard.superadmin.status": "Status",
    "dashboard.superadmin.active": "Active",
    "dashboard.superadmin.no_teachers": "No teachers found",
    "dashboard.superadmin.no_students": "No students found",
    "dashboard.superadmin.pending_enrollments": "Pending Enrollments",
    "dashboard.superadmin.pending_enrollments_desc": "Manage pending enrollment requests for paid courses",
    "dashboard.superadmin.no_pending_enrollments": "No pending enrollments",
    "dashboard.superadmin.categories": "Categories",
    "dashboard.superadmin.manage_categories": "Manage course categories",
    "dashboard.superadmin.create_category": "Create Category",
    "dashboard.superadmin.no_categories": "No categories found",
    "dashboard.superadmin.course_stats": "Course Statistics",
    "dashboard.superadmin.course_stats_desc": "Detailed view of all courses and student counts",
    "dashboard.superadmin.no_courses": "No courses found",
    "dashboard.superadmin.teacher_stats": "Teacher Statistics",
    "dashboard.superadmin.teacher_stats_desc": "Detailed view of all teachers with their courses and students",
    
    // Dashboard - Teacher
    "dashboard.teacher.title": "Teacher Dashboard",
    "dashboard.teacher.welcome": "Welcome back",
    "dashboard.teacher.my_courses": "My Courses",
    "dashboard.teacher.students": "Students",
    "dashboard.teacher.total_enrollments": "Total Enrollments",
    "dashboard.teacher.create_course": "Create Course",
    "dashboard.teacher.manage_courses": "Manage your courses",
    "dashboard.teacher.no_courses": "You haven't created any courses yet",
    "dashboard.teacher.get_started": "Get started by creating your first course",
    "dashboard.teacher.pending_enrollments": "Pending Enrollments",
    "dashboard.teacher.pending_enrollments_desc": "Confirm student payments to unlock course access",
    "dashboard.teacher.pending": "pending",
    "dashboard.teacher.all_enrollments": "All Enrollments",
    "dashboard.teacher.all_enrollments_desc": "View all students enrolled in your courses",
    "dashboard.teacher.view_enrollments": "View Enrollments",
    "dashboard.teacher.filter_all": "All",
    "dashboard.teacher.filter_confirmed": "Confirmed",
    "dashboard.teacher.filter_pending": "Pending",
    "dashboard.teacher.filter_free": "Free",
    "dashboard.teacher.enrollment_status": "Status",
    "dashboard.teacher.student_phone": "Student Phone",
    "dashboard.teacher.no_enrollments": "No enrollments yet",
    "dashboard.teacher.no_enrollments_desc": "Students enrolled in your courses will appear here",
    "dashboard.teacher.course": "Course",
    
    // Dashboard - Student
    "dashboard.student.title": "Student Dashboard",
    "dashboard.student.welcome": "Welcome back",
    "dashboard.student.continue": "Continue your learning journey",
    "dashboard.student.enrolled_courses": "Enrolled Courses",
    "dashboard.student.completed": "Completed",
    "dashboard.student.avg_progress": "Average Progress",
    "dashboard.student.my_courses": "My Courses",
    "dashboard.student.continue_learning": "Continue Learning",
    "dashboard.student.progress": "Progress",
    "dashboard.student.resume": "Resume",
    "dashboard.student.no_courses": "You haven't enrolled in any courses yet",
    "dashboard.student.explore": "Explore our courses and start learning today",
    
    // Create Teacher Dialog
    "dialog.create_teacher.title": "Create Teacher Account",
    "dialog.create_teacher.description": "Create a new teacher account. A random password will be generated.",
    "dialog.create_teacher.full_name": "Full Name",
    "dialog.create_teacher.email": "Email",
    "dialog.create_teacher.cancel": "Cancel",
    "dialog.create_teacher.create": "Create",
    "dialog.create_teacher.creating": "Creating...",
    "dialog.create_teacher.success": "Teacher created successfully!",
    "dialog.create_teacher.password_label": "Generated Password",
    "dialog.create_teacher.password_note": "Please save this password and share it with the teacher. It will not be shown again.",
    "dialog.create_teacher.copy_password": "Copy Password",
    "dialog.create_teacher.password_copied": "Password copied!",
    "dialog.create_teacher.password_copied_desc": "Password copied to clipboard",
    "dialog.create_teacher.failed": "Failed to create teacher",
    "dialog.create_teacher.validation_error": "Validation error",
    "dialog.create_teacher.fill_all_fields": "Please fill in all fields",
    
    // Delete Confirmation
    "dialog.delete.title": "Confirm Deletion",
    "dialog.delete.teacher_message": "Are you sure you want to delete this teacher? This action cannot be undone.",
    "dialog.delete.student_message": "Are you sure you want to delete this student? This action cannot be undone.",
    "dialog.delete.category_message": "Are you sure you want to delete this category? Categories with existing courses cannot be deleted.",
    "dialog.delete.confirm": "Yes, Delete",
    "dialog.delete.cancel": "Cancel",
    "dialog.delete.deleting": "Deleting...",
    "dialog.delete.teacher_success": "Teacher deleted successfully",
    "dialog.delete.teacher_success_desc": "The teacher account has been removed from the platform",
    "dialog.delete.student_success": "Student deleted successfully",
    "dialog.delete.student_success_desc": "The student account has been removed from the platform",
    "dialog.delete.failed": "Delete failed",
    
    // Category Dialog
    "dialog.category.create_title": "Create New Category",
    "dialog.category.create_description": "Create a new category to organize courses",
    "dialog.category.edit_title": "Edit Category",
    "dialog.category.edit_description": "Update category information",
    "dialog.category.name": "Category Name",
    "dialog.category.name_placeholder": "e.g., Programming, Mathematics, Science",
    "dialog.category.description": "Description",
    "dialog.category.description_placeholder": "Brief description of the category (optional)",
    "dialog.category.create": "Create",
    "dialog.category.update": "Update",
    "dialog.category.saving": "Saving...",
    
    // Reset Password Dialog
    "dialog.reset_password.title": "Reset Teacher Password",
    "dialog.reset_password.description": "Enter a new password for the teacher account",
    
    // Common Actions
    "action.view": "View",
    "action.edit": "Edit",
    "action.delete": "Delete",
    "action.save": "Save",
    "action.cancel": "Cancel",
    "action.confirm_delete": "Confirm Delete",
    "action.edit_lesson": "Edit Lesson",
    "action.edit_quiz": "Edit Quiz",
    "action.edit_course": "Edit Course",
    "confirm.delete_lesson": "Are you sure you want to delete this lesson?",
    "confirm.delete_quiz": "Are you sure you want to delete this quiz?",
    "confirm.delete_course": "Are you sure you want to delete this course? All lessons and quizzes will be deleted.",
    "confirm.delete_warning": "This action cannot be undone.",
    "action.submit": "Submit",
    "action.back": "Back",
    "action.next": "Next",
    "action.close": "Close",
    "action.add_lesson": "Add Lesson",
    "action.add_quiz": "Add Quiz",
    "action.view_public": "View Public Page",
    "action.confirm": "Confirm",
    "action.send_reset_link": "Send Reset Link",
    "action.sending": "Sending...",
    "action.back_to_login": "Back to Login",
    "action.reset_password": "Reset Password",
    "action.resetting": "Resetting...",
    "action.request_new_link": "Request New Link",
    "action.go_to_login": "Go to Login",
    
    // Button Labels
    "button.confirm": "Confirm",
    
    // Manage Course
    "manage.lessons_desc": "Manage your course lessons and add new content",
    "manage.no_lessons": "No lessons yet. Add your first lesson!",
    "manage.quizzes": "Quizzes",
    "manage.no_quizzes": "No quizzes for this lesson yet.",
    "manage.update_course_info": "Update course details like title and price",
    
    // Form Labels
    "label.course_title": "Course Title",
    "label.lesson_title": "Lesson Title",
    "label.youtube_url": "YouTube URL",
    "label.duration_minutes": "Duration (minutes)",
    "label.lesson_order": "Order",
    "label.minutes": "minutes",
    "label.quiz_title": "Quiz Title",
    "label.quiz_description": "Quiz Description",
    "label.deadline": "Deadline",
    "label.category": "Category",
    "label.description": "Description",
    "label.price": "Price",
    "label.course_thumbnail": "Course Thumbnail",
    "label.email": "Email",
    "label.new_password": "New Password",
    "label.confirm_password": "Confirm Password",
    "label.student": "Student",
    "label.course": "Course",
    "label.teacher": "Teacher",
    "label.enrolled_at": "Enrolled At",
    "label.actions": "Actions",
    "label.no_description": "No description",
    "label.lessons": "Lessons",
    "label.total_students": "Total Students",
    "label.total_lessons": "Total Lessons",
    "label.confirmed": "Confirmed",
    "label.pending": "Pending",
    "label.free": "Free",
    "label.courses": "Courses",
    "label.whatsapp": "WhatsApp",
    "label.course_details": "Course Details",
    "label.students": "Students",
    
    // Placeholders
    "placeholder.lesson_title": "e.g., Introduction to Programming",
    "placeholder.quiz_title": "e.g., Unit 1 Quiz",
    "placeholder.quiz_description": "Answer the following questions...",
    
    // Placeholders
    "placeholder.course_title": "Introduction to Web Development",
    "placeholder.course_description": "A comprehensive course that covers...",
    "placeholder.what_you_learn": "Build web applications\nUnderstand JavaScript\nWork with APIs",
    "placeholder.price": "25000",
    
    // Categories
    "category.programming": "Programming",
    "category.mathematics": "Mathematics",
    "category.science": "Science",
    "category.languages": "Languages",
    "category.business": "Business",
    "category.design": "Design",
    
    // Status
    "status.pending": "Pending",
    "status.confirmed": "Confirmed",
    "status.active": "Active",
    "status.inactive": "Inactive",
    
    // Footer
    "footer.tagline": "Transform your future with expert-led online courses",
    "footer.platform": "Platform",
    "footer.about": "About Us",
    "footer.how_it_works": "How It Works",
    "footer.careers": "Careers",
    "footer.blog": "Blog",
    "footer.courses": "Courses",
    "footer.browse_courses": "Browse Courses",
    "footer.become_teacher": "Become a Teacher",
    "footer.become_teacher_message": "Hello, I would like to become a teacher on Abraj Educational Platform",
    "footer.pricing": "Pricing",
    "footer.support": "Support",
    "footer.help_center": "Help Center",
    "footer.contact_us": "Contact Us",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Terms of Service",
    "footer.copyright": "© All rights reserved.",
    
    // About Us Page
    "about.title": "About Us",
    "about.subtitle": "A leading educational platform aimed at empowering learners worldwide",
    "about.mission_title": "Our Mission",
    "about.mission_desc": "We strive to provide high-quality education accessible to everyone. We believe that education is the key to success, and we work to provide an excellent learning environment that brings together the best teachers and students passionate about learning.",
    "about.vision_title": "Our Vision",
    "about.vision_desc": "We aspire to be the leading educational platform in the region, where everyone can access excellent education that helps them achieve their professional and personal goals. We seek to build a vibrant educational community that supports continuous learning and self-development.",
    "about.features_title": "Why Choose Abraj Educational Platform?",
    "about.feature_quality_title": "High-Quality Content",
    "about.feature_quality_desc": "Carefully designed courses by experts in their fields",
    "about.feature_teachers_title": "Professional Teachers",
    "about.feature_teachers_desc": "Learn from the best teachers with extensive experience",
    "about.feature_courses_title": "Content Diversity",
    "about.feature_courses_desc": "A wide range of courses in various fields",
    "about.feature_progress_title": "Progress Tracking",
    "about.feature_progress_desc": "Monitor your progress and achieve your educational goals",
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("language");
    return (saved as Language) || "ar"; // Default to Arabic
  });

  const isRTL = language === "ar";

  useEffect(() => {
    localStorage.setItem("language", language);
    document.documentElement.lang = language;
    document.documentElement.dir = isRTL ? "rtl" : "ltr";
    
    // Update page title
    document.title = language === "ar" 
      ? "منصة الابتكار - أتقن مهارات جديدة" 
      : "Innovation Platform - Master New Skills";
  }, [language, isRTL]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
